'use strict'

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('items', [
      {
        id: 1,
        order_id: 1,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 2,
        order_id: 1,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 3,
        order_id: 1,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 4,
        order_id: 1,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 5,
        order_id: 1,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 6,
        order_id: 1,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 7,
        order_id: 1,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 8,
        order_id: 1,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 9,
        order_id: 1,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 10,
        order_id: 1,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 11,
        order_id: 2,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 12,
        order_id: 2,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 13,
        order_id: 2,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 14,
        order_id: 2,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 15,
        order_id: 2,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 16,
        order_id: 2,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 17,
        order_id: 2,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 18,
        order_id: 2,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 19,
        order_id: 2,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 20,
        order_id: 2,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 21,
        order_id: 1,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 22,
        order_id: 1,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 23,
        order_id: 1,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 24,
        order_id: 1,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 25,
        order_id: 3,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 26,
        order_id: 3,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 27,
        order_id: 3,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 28,
        order_id: 3,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 29,
        order_id: 3,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 30,
        order_id: 3,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 31,
        order_id: 4,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 32,
        order_id: 4,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 33,
        order_id: 4,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 34,
        order_id: 4,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 35,
        order_id: 4,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 36,
        order_id: 4,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 37,
        order_id: 4,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 38,
        order_id: 4,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 39,
        order_id: 4,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 40,
        order_id: 4,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 41,
        order_id: 5,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 42,
        order_id: 5,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 43,
        order_id: 5,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 44,
        order_id: 5,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 45,
        order_id: 5,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 46,
        order_id: 5,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 47,
        order_id: 5,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 48,
        order_id: 5,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 49,
        order_id: 5,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 50,
        order_id: 5,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 51,
        order_id: 6,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 52,
        order_id: 6,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 53,
        order_id: 6,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 54,
        order_id: 6,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 55,
        order_id: 6,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 56,
        order_id: 6,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 57,
        order_id: 6,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 58,
        order_id: 6,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 59,
        order_id: 6,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 60,
        order_id: 6,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 61,
        order_id: 7,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 62,
        order_id: 7,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 63,
        order_id: 7,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 64,
        order_id: 7,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 65,
        order_id: 7,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 66,
        order_id: 7,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 67,
        order_id: 7,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 68,
        order_id: 7,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 69,
        order_id: 7,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 70,
        order_id: 7,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 71,
        order_id: 8,
        provider_id: 1,
        product_id: 7,
        product_name: 'Cheetos',
        amount: 2,
        total_price: 8.66,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 72,
        order_id: 8,
        provider_id: 1,
        product_id: 2,
        product_name: 'Mucilon',
        amount: 7,
        total_price: 67.13,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 73,
        order_id: 8,
        provider_id: 1,
        product_id: 6,
        product_name: 'Ruffles',
        amount: 3,
        total_price: 47.67,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 74,
        order_id: 8,
        provider_id: 1,
        product_id: 4,
        product_name: 'Passa Tempo',
        amount: 5,
        total_price: 18,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 75,
        order_id: 8,
        provider_id: 1,
        product_id: 8,
        product_name: 'Doritos',
        amount: 1,
        total_price: 14.6,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 76,
        order_id: 8,
        provider_id: 1,
        product_id: 9,
        product_name: 'Fandangos',
        amount: 4,
        total_price: 14.4,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 77,
        order_id: 8,
        provider_id: 1,
        product_id: 5,
        product_name: 'Nescau 2.0',
        amount: 2,
        total_price: 20.46,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 78,
        order_id: 8,
        provider_id: 1,
        product_id: 1,
        product_name: 'KitKat',
        amount: 5,
        total_price: 25,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 79,
        order_id: 8,
        provider_id: 1,
        product_id: 3,
        product_name: 'Ninho',
        amount: 2,
        total_price: 25.2,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: 80,
        order_id: 8,
        provider_id: 1,
        product_id: 12,
        product_name: 'Lattitude',
        amount: 1,
        total_price: 200,
        created_at: new Date(),
        updated_at: new Date()
      }

    ], {})
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('items', null, {})
  }
}
